"""initial schema

Revision ID: 571e9c005b42
Revises: 
Create Date: 2026-07-26 09:48:47.537448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '571e9c005b42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extensions the schema depends on. Created here as well as in the docker
    # init script so that `alembic upgrade head` alone is enough to build the
    # database — in CI, or on a managed Postgres where no init script runs.
    #
    #   pg_trgm     fuzzy matching on subject and institution names
    #   unaccent    "prijimacky" has to find "přijímačky"
    #   btree_gist  equality on helper_id combined with range overlap in the
    #               availability exclusion constraint
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # unaccent() is STABLE, which bars it from expression indexes. This wrapper
    # is the standard workaround: the dictionary is pinned, so the IMMUTABLE
    # promise actually holds.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION immutable_unaccent(text)
        RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
        AS $$ SELECT public.unaccent('public.unaccent'::regdictionary, $1) $$
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('depth', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('university', 'faculty', 'school', 'exam_body', 'other', name='institution_kind'), nullable=False),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('site_url', sa.String(length=512), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['institutions.id'], name=op.f('fk_institutions_parent_id_institutions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutions')),
    sa.UniqueConstraint('code', name=op.f('uq_institutions_code'))
    )
    op.create_index('ix_institutions_active_sort', 'institutions', ['is_active', 'sort'], unique=False)
    op.create_index(op.f('ix_institutions_parent_id'), 'institutions', ['parent_id'], unique=False)
    op.create_index('ix_institutions_path_prefix', 'institutions', ['path'], unique=False, postgresql_ops={'path': 'text_pattern_ops'})
    op.create_table('item_categories',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('allows_rent', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('allows_sale', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_item_categories_code'))
    )
    op.create_table('languages',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_languages'))
    )
    op.create_table('moderation_reviews',
    sa.Column('entity_type', sa.Enum('helper_profile', 'offer', 'request', 'item', 'material', name='moderated_entity'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Enum('auto_ok', 'needs_review', 'rejected', name='moderation_verdict'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=96), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_reviews'))
    )
    op.create_index('ix_moderation_reviews_entity', 'moderation_reviews', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index('ix_moderation_reviews_queue', 'moderation_reviews', ['verdict', 'created_at'], unique=False)
    op.create_table('partners',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=240), nullable=True),
    sa.Column('payout_model', sa.Enum('cpc', 'cpl', 'fixed', name='payout_model'), server_default='cpc', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners')),
    sa.UniqueConstraint('code', name=op.f('uq_partners_code'))
    )
    op.create_table('service_types',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('requires_subject', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_institution', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('default_price_unit', sa.String(length=16), nullable=True),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_types')),
    sa.UniqueConstraint('code', name=op.f('uq_service_types_code'))
    )
    op.create_table('subjects',
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('depth', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('kind', sa.Enum('group', 'leaf', name='node_kind'), server_default='leaf', nullable=False),
    sa.Column('external_code', sa.String(length=32), nullable=True),
    sa.Column('synonyms', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['subjects.id'], name=op.f('fk_subjects_parent_id_subjects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('slug', name=op.f('uq_subjects_slug'))
    )
    op.create_index('ix_subjects_active_sort', 'subjects', ['is_active', 'sort'], unique=False)
    op.create_index(op.f('ix_subjects_parent_id'), 'subjects', ['parent_id'], unique=False)
    op.create_index('ix_subjects_path_prefix', 'subjects', ['path'], unique=False, postgresql_ops={'path': 'text_pattern_ops'})
    op.create_index('ix_subjects_synonyms', 'subjects', ['synonyms'], unique=False, postgresql_using='gin')
    op.create_table('institution_i18n',
    sa.Column('institution_id', sa.BigInteger(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'cs', 'en', 'uk', name='ui_lang'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_institution_i18n_institution_id_institutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('institution_id', 'lang', name=op.f('pk_institution_i18n'))
    )
    op.create_index('ix_institution_i18n_name_trgm', 'institution_i18n', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('item_category_i18n',
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'cs', 'en', 'uk', name='ui_lang'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('hint', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], name=op.f('fk_item_category_i18n_category_id_item_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'lang', name=op.f('pk_item_category_i18n'))
    )
    op.create_table('language_i18n',
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'cs', 'en', 'uk', name='ui_lang'), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_language_i18n_language_code_languages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('language_code', 'lang', name=op.f('pk_language_i18n'))
    )
    op.create_table('partner_offers',
    sa.Column('partner_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('logo_text', sa.String(length=4), nullable=True),
    sa.Column('logo_bg', sa.String(length=9), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_partner_offers_partner_id_partners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_offers'))
    )
    op.create_index(op.f('ix_partner_offers_partner_id'), 'partner_offers', ['partner_id'], unique=False)
    op.create_table('service_type_i18n',
    sa.Column('service_type_id', sa.BigInteger(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'cs', 'en', 'uk', name='ui_lang'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('hint', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], name=op.f('fk_service_type_i18n_service_type_id_service_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_type_id', 'lang', name=op.f('pk_service_type_i18n'))
    )
    op.create_table('student_chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('institution_id', sa.BigInteger(), nullable=True),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_student_chats_institution_id_institutions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_chats'))
    )
    op.create_index(op.f('ix_student_chats_institution_id'), 'student_chats', ['institution_id'], unique=False)
    op.create_table('subject_i18n',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'cs', 'en', 'uk', name='ui_lang'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_subject_i18n_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'lang', name=op.f('pk_subject_i18n'))
    )
    op.create_index('ix_subject_i18n_name_trgm', 'subject_i18n', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('ui_lang', sa.Enum('ru', 'cs', 'en', 'uk', name='ui_lang'), server_default='ru', nullable=False),
    sa.Column('spoken_langs', postgresql.ARRAY(sa.String(length=8)), server_default='{}', nullable=False),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('institution_id', sa.BigInteger(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_users_institution_id_institutions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tg_id', name=op.f('uq_users_tg_id'))
    )
    op.create_index(op.f('ix_users_institution_id'), 'users', ['institution_id'], unique=False)
    op.create_index('ix_users_spoken_langs', 'users', ['spoken_langs'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_users_tg_username'), 'users', ['tg_username'], unique=False)
    op.create_table('help_requests',
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'cs', 'en', 'uk', 'xx', name='content_lang'), server_default='ru', nullable=False),
    sa.Column('service_type_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_id', sa.BigInteger(), nullable=True),
    sa.Column('institution_id', sa.BigInteger(), nullable=True),
    sa.Column('deadline_on', sa.Date(), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), server_default='CZK', nullable=False),
    sa.Column('budget_unit', sa.Enum('hour', 'lesson', 'work', 'day', 'week', 'month', 'semester', 'item', 'negotiable', name='price_unit'), nullable=True),
    sa.Column('langs', postgresql.ARRAY(sa.String(length=8)), server_default='{}', nullable=False),
    sa.Column('work_format', sa.Enum('online', 'offline', 'both', name='work_format'), server_default='both', nullable=False),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', 'expired', name='request_status'), server_default='draft', nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_help_requests_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_help_requests_institution_id_institutions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], name=op.f('fk_help_requests_service_type_id_service_types'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_help_requests_subject_id_subjects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_help_requests'))
    )
    op.create_index(op.f('ix_help_requests_author_id'), 'help_requests', ['author_id'], unique=False)
    op.create_index('ix_help_requests_langs', 'help_requests', ['langs'], unique=False, postgresql_using='gin')
    op.create_index('ix_help_requests_match', 'help_requests', ['subject_id', 'institution_id', 'service_type_id'], unique=False)
    op.create_index('ix_help_requests_open', 'help_requests', ['status', 'expires_at'], unique=False)
    op.create_table('helper_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('headline', sa.String(length=160), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('about_lang', sa.Enum('ru', 'cs', 'en', 'uk', 'xx', name='content_lang'), server_default='ru', nullable=False),
    sa.Column('raw_intro', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending', 'published', 'hidden', 'banned', name='publish_status'), server_default='draft', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_format', sa.Enum('online', 'offline', 'both', name='work_format'), server_default='both', nullable=False),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('place_note', sa.String(length=240), nullable=True),
    sa.Column('response_minutes_avg', sa.Integer(), nullable=True),
    sa.Column('deals_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('reviews_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0 AND rating <= 5)', name=op.f('ck_helper_profiles_rating_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_helper_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_helper_profiles'))
    )
    op.create_index('ix_helper_profiles_status_published', 'helper_profiles', ['status', 'published_at'], unique=False)
    op.create_table('items',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('rent', 'sale', name='item_kind'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lang', sa.Enum('ru', 'cs', 'en', 'uk', 'xx', name='content_lang'), server_default='ru', nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(length=3), server_default='CZK', nullable=False),
    sa.Column('price_unit', sa.Enum('hour', 'lesson', 'work', 'day', 'week', 'month', 'semester', 'item', 'negotiable', name='price_unit'), server_default='day', nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('condition', sa.Enum('new', 'good', 'used', name='item_condition'), nullable=True),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('pickup_note', sa.String(length=240), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'reserved', 'hidden', 'archived', name='item_status'), server_default='draft', nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deposit_amount IS NULL OR deposit_amount >= 0', name=op.f('ck_items_deposit_non_negative')),
    sa.CheckConstraint('price_amount IS NULL OR price_amount >= 0', name=op.f('ck_items_price_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], name=op.f('fk_items_category_id_item_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_items_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_items_subject_id_subjects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_index('ix_items_attrs', 'items', ['attrs'], unique=False, postgresql_using='gin')
    op.create_index('ix_items_browse', 'items', ['status', 'kind', 'category_id'], unique=False)
    op.create_index('ix_items_city', 'items', ['city'], unique=False)
    op.create_index(op.f('ix_items_owner_id'), 'items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_items_subject_id'), 'items', ['subject_id'], unique=False)
    op.create_table('materials',
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=True),
    sa.Column('institution_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('notes', 'past_exams', 'template', 'course', 'other', name='material_kind'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lang', sa.Enum('ru', 'cs', 'en', 'uk', 'xx', name='content_lang'), server_default='ru', nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('access', sa.Enum('free', 'on_request', 'paid', name='material_access'), server_default='on_request', nullable=False),
    sa.Column('price_stars', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'reserved', 'hidden', 'archived', name='item_status'), server_default='draft', nullable=False),
    sa.Column('downloads_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("access <> 'paid' OR price_stars IS NOT NULL", name=op.f('ck_materials_paid_needs_price')),
    sa.CheckConstraint('price_stars IS NULL OR price_stars > 0', name=op.f('ck_materials_stars_positive')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_materials_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_materials_institution_id_institutions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_materials_subject_id_subjects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    op.create_index(op.f('ix_materials_author_id'), 'materials', ['author_id'], unique=False)
    op.create_index('ix_materials_browse', 'materials', ['status', 'kind', 'subject_id'], unique=False)
    op.create_index(op.f('ix_materials_institution_id'), 'materials', ['institution_id'], unique=False)
    op.create_index(op.f('ix_materials_subject_id'), 'materials', ['subject_id'], unique=False)
    op.create_table('partner_offer_i18n',
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'cs', 'en', 'uk', name='ui_lang'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=240), nullable=True),
    sa.Column('price_text', sa.String(length=64), nullable=True),
    sa.Column('context_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['partner_offers.id'], name=op.f('fk_partner_offer_i18n_offer_id_partner_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', 'lang', name=op.f('pk_partner_offer_i18n'))
    )
    op.create_table('placements',
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('slot', sa.Enum('screen_life', 'screen_nostrification', 'screen_languages', 'screen_search_empty', 'after_request_created', 'profile_footer', name='placement_slot'), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('weight', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['partner_offers.id'], name=op.f('fk_placements_offer_id_partner_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placements'))
    )
    op.create_index('ix_placements_conditions', 'placements', ['conditions'], unique=False, postgresql_using='gin')
    op.create_index('ix_placements_slot_active', 'placements', ['slot', 'is_active', 'priority'], unique=False)
    op.create_table('search_queries',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'cs', 'en', 'uk', 'xx', name='content_lang'), nullable=True),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('corrected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('parser', sa.String(length=64), nullable=True),
    sa.Column('took', sa.Interval(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_queries_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_queries'))
    )
    op.create_index('ix_search_queries_created', 'search_queries', ['created_at'], unique=False)
    op.create_index('ix_search_queries_empty', 'search_queries', ['results_count', 'created_at'], unique=False)
    op.create_index('ix_search_queries_parsed', 'search_queries', ['parsed'], unique=False, postgresql_using='gin')
    op.create_table('user_education',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('institution_id', sa.BigInteger(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('started_year', sa.Integer(), nullable=True),
    sa.Column('finished_year', sa.Integer(), nullable=True),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_user_education_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_education_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_education'))
    )
    op.create_index(op.f('ix_user_education_institution_id'), 'user_education', ['institution_id'], unique=False)
    op.create_index(op.f('ix_user_education_user_id'), 'user_education', ['user_id'], unique=False)
    op.create_table('availability_slots',
    sa.Column('helper_id', sa.BigInteger(), nullable=False),
    sa.Column('period', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('note', sa.String(length=240), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    postgresql.ExcludeConstraint((sa.column('helper_id'), '='), (sa.column('period'), '&&'), using='gist', name='availability_slots_no_overlap'),
    sa.ForeignKeyConstraint(['helper_id'], ['helper_profiles.user_id'], name=op.f('fk_availability_slots_helper_id_helper_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_slots'))
    )
    op.create_index('ix_availability_slots_period', 'availability_slots', ['period'], unique=False, postgresql_using='gist')
    op.create_table('offers',
    sa.Column('helper_id', sa.BigInteger(), nullable=False),
    sa.Column('service_type_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=True),
    sa.Column('institution_id', sa.BigInteger(), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(length=3), server_default='CZK', nullable=False),
    sa.Column('price_unit', sa.Enum('hour', 'lesson', 'work', 'day', 'week', 'month', 'semester', 'item', 'negotiable', name='price_unit'), server_default='hour', nullable=False),
    sa.Column('langs', postgresql.ARRAY(sa.String(length=8)), server_default='{}', nullable=False),
    sa.Column('work_format', sa.Enum('online', 'offline', 'both', name='work_format'), server_default='both', nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_amount IS NULL OR price_amount >= 0', name=op.f('ck_offers_price_non_negative')),
    sa.ForeignKeyConstraint(['helper_id'], ['helper_profiles.user_id'], name=op.f('fk_offers_helper_id_helper_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_offers_institution_id_institutions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], name=op.f('fk_offers_service_type_id_service_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_offers_subject_id_subjects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers')),
    sa.UniqueConstraint('helper_id', 'service_type_id', 'subject_id', 'institution_id', name='uq_offers_axes', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_offers_attrs', 'offers', ['attrs'], unique=False, postgresql_using='gin')
    op.create_index('ix_offers_helper', 'offers', ['helper_id'], unique=False)
    op.create_index('ix_offers_langs', 'offers', ['langs'], unique=False, postgresql_using='gin')
    op.create_index('ix_offers_lookup', 'offers', ['service_type_id', 'subject_id', 'institution_id', 'is_active'], unique=False)
    op.create_index('ix_offers_price', 'offers', ['price_currency', 'price_amount'], unique=False)
    op.create_table('placement_events',
    sa.Column('placement_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('impression', 'click', name='placement_event_kind'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], name=op.f('fk_placement_events_placement_id_placements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_placement_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_events'))
    )
    op.create_index('ix_placement_events_rollup', 'placement_events', ['placement_id', 'kind', 'created_at'], unique=False)
    op.create_table('request_responses',
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('helper_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(length=3), server_default='CZK', nullable=False),
    sa.Column('status', sa.Enum('sent', 'read', 'accepted', 'declined', name='response_status'), server_default='sent', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_amount IS NULL OR price_amount >= 0', name=op.f('ck_request_responses_price_non_negative')),
    sa.ForeignKeyConstraint(['helper_id'], ['helper_profiles.user_id'], name=op.f('fk_request_responses_helper_id_helper_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['help_requests.id'], name=op.f('fk_request_responses_request_id_help_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_responses')),
    sa.UniqueConstraint('request_id', 'helper_id', name='uq_request_responses_pair')
    )
    op.create_index('ix_request_responses_helper', 'request_responses', ['helper_id', 'status'], unique=False)
    op.create_table('weekly_availability',
    sa.Column('helper_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint('start_minute >= 0 AND end_minute <= 1440 AND start_minute < end_minute', name=op.f('ck_weekly_availability_minute_range')),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_weekly_availability_weekday_range')),
    sa.ForeignKeyConstraint(['helper_id'], ['helper_profiles.user_id'], name=op.f('fk_weekly_availability_helper_id_helper_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_availability'))
    )
    op.create_index('ix_weekly_availability_helper_weekday', 'weekly_availability', ['helper_id', 'weekday'], unique=False)
    op.create_table('contacts',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('helper_id', sa.BigInteger(), nullable=False),
    sa.Column('offer_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('intro_text', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['helper_id'], ['helper_profiles.user_id'], name=op.f('fk_contacts_helper_id_helper_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_contacts_offer_id_offers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['help_requests.id'], name=op.f('fk_contacts_request_id_help_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_contacts_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_helper_id'), 'contacts', ['helper_id'], unique=False)
    op.create_index(op.f('ix_contacts_student_id'), 'contacts', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP FUNCTION IF EXISTS immutable_unaccent(text)")
    # Extensions are left in place: other databases on the same cluster may
    # rely on them, and dropping them is not this migration's business.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_student_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_helper_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_weekly_availability_helper_weekday', table_name='weekly_availability')
    op.drop_table('weekly_availability')
    op.drop_index('ix_request_responses_helper', table_name='request_responses')
    op.drop_table('request_responses')
    op.drop_index('ix_placement_events_rollup', table_name='placement_events')
    op.drop_table('placement_events')
    op.drop_index('ix_offers_price', table_name='offers')
    op.drop_index('ix_offers_lookup', table_name='offers')
    op.drop_index('ix_offers_langs', table_name='offers', postgresql_using='gin')
    op.drop_index('ix_offers_helper', table_name='offers')
    op.drop_index('ix_offers_attrs', table_name='offers', postgresql_using='gin')
    op.drop_table('offers')
    op.drop_index('ix_availability_slots_period', table_name='availability_slots', postgresql_using='gist')
    op.drop_table('availability_slots')
    op.drop_index(op.f('ix_user_education_user_id'), table_name='user_education')
    op.drop_index(op.f('ix_user_education_institution_id'), table_name='user_education')
    op.drop_table('user_education')
    op.drop_index('ix_search_queries_parsed', table_name='search_queries', postgresql_using='gin')
    op.drop_index('ix_search_queries_empty', table_name='search_queries')
    op.drop_index('ix_search_queries_created', table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index('ix_placements_slot_active', table_name='placements')
    op.drop_index('ix_placements_conditions', table_name='placements', postgresql_using='gin')
    op.drop_table('placements')
    op.drop_table('partner_offer_i18n')
    op.drop_index(op.f('ix_materials_subject_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_institution_id'), table_name='materials')
    op.drop_index('ix_materials_browse', table_name='materials')
    op.drop_index(op.f('ix_materials_author_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_items_subject_id'), table_name='items')
    op.drop_index(op.f('ix_items_owner_id'), table_name='items')
    op.drop_index('ix_items_city', table_name='items')
    op.drop_index('ix_items_browse', table_name='items')
    op.drop_index('ix_items_attrs', table_name='items', postgresql_using='gin')
    op.drop_table('items')
    op.drop_index('ix_helper_profiles_status_published', table_name='helper_profiles')
    op.drop_table('helper_profiles')
    op.drop_index('ix_help_requests_open', table_name='help_requests')
    op.drop_index('ix_help_requests_match', table_name='help_requests')
    op.drop_index('ix_help_requests_langs', table_name='help_requests', postgresql_using='gin')
    op.drop_index(op.f('ix_help_requests_author_id'), table_name='help_requests')
    op.drop_table('help_requests')
    op.drop_index(op.f('ix_users_tg_username'), table_name='users')
    op.drop_index('ix_users_spoken_langs', table_name='users', postgresql_using='gin')
    op.drop_index(op.f('ix_users_institution_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_subject_i18n_name_trgm', table_name='subject_i18n', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('subject_i18n')
    op.drop_index(op.f('ix_student_chats_institution_id'), table_name='student_chats')
    op.drop_table('student_chats')
    op.drop_table('service_type_i18n')
    op.drop_index(op.f('ix_partner_offers_partner_id'), table_name='partner_offers')
    op.drop_table('partner_offers')
    op.drop_table('language_i18n')
    op.drop_table('item_category_i18n')
    op.drop_index('ix_institution_i18n_name_trgm', table_name='institution_i18n', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('institution_i18n')
    op.drop_index('ix_subjects_synonyms', table_name='subjects', postgresql_using='gin')
    op.drop_index('ix_subjects_path_prefix', table_name='subjects', postgresql_ops={'path': 'text_pattern_ops'})
    op.drop_index(op.f('ix_subjects_parent_id'), table_name='subjects')
    op.drop_index('ix_subjects_active_sort', table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('service_types')
    op.drop_table('partners')
    op.drop_index('ix_moderation_reviews_queue', table_name='moderation_reviews')
    op.drop_index('ix_moderation_reviews_entity', table_name='moderation_reviews')
    op.drop_table('moderation_reviews')
    op.drop_table('languages')
    op.drop_table('item_categories')
    op.drop_index('ix_institutions_path_prefix', table_name='institutions', postgresql_ops={'path': 'text_pattern_ops'})
    op.drop_index(op.f('ix_institutions_parent_id'), table_name='institutions')
    op.drop_index('ix_institutions_active_sort', table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
