"""record who started the bot and what they did

Revision ID: fbdbb4c11417
Revises: fe3b01682ded
Create Date: 2026-07-26 13:34:05.953093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbdbb4c11417'
down_revision: Union[str, Sequence[str], None] = 'fe3b01682ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_events',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('bot_start', 'bot_message', 'bot_blocked', 'bot_unblocked', 'app_open', 'search', 'helper_view', 'contact', 'request_created', 'profile_published', name='user_event_kind'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_events'))
    )
    op.create_index('ix_user_events_kind', 'user_events', ['kind', 'created_at'], unique=False)
    op.create_index('ix_user_events_payload', 'user_events', ['payload'], unique=False, postgresql_using='gin')
    op.create_index('ix_user_events_person', 'user_events', ['user_id', 'created_at'], unique=False)
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('bot_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('bot_can_message', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('source', sa.String(length=64), nullable=True))
    op.create_index('ix_users_reachable', 'users', ['bot_can_message', 'unsubscribed_at', 'bot_started_at'], unique=False)
    op.create_index(op.f('ix_users_source'), 'users', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_source'), table_name='users')
    op.drop_index('ix_users_reachable', table_name='users')
    op.drop_column('users', 'source')
    op.drop_column('users', 'unsubscribed_at')
    op.drop_column('users', 'bot_can_message')
    op.drop_column('users', 'bot_started_at')
    op.drop_column('users', 'is_premium')
    op.drop_index('ix_user_events_person', table_name='user_events')
    op.drop_index('ix_user_events_payload', table_name='user_events', postgresql_using='gin')
    op.drop_index('ix_user_events_kind', table_name='user_events')
    op.drop_table('user_events')
    # ### end Alembic commands ###
