"""index normalised names and bound availability

Revision ID: fe3b01682ded
Revises: 571e9c005b42
Create Date: 2026-07-26 10:44:06.607263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3b01682ded'
down_revision: Union[str, Sequence[str], None] = '571e9c005b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate does not detect CheckConstraints, so this one is by hand.
    # tstzrange allows unbounded and empty ranges; neither is a thing a person
    # offers, and both would crash every reader that compares the bounds.
    op.execute("DELETE FROM availability_slots WHERE lower_inf(period) OR upper_inf(period) OR isempty(period)")
    op.create_check_constraint(
        "period_is_bounded",
        "availability_slots",
        "NOT lower_inf(period) AND NOT upper_inf(period) AND NOT isempty(period)",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institution_i18n_name_trgm'), table_name='institution_i18n', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('ix_institution_i18n_name_trgm', 'institution_i18n', [sa.literal_column('immutable_unaccent(lower(name))')], unique=False, postgresql_using='gin', postgresql_ops={'immutable_unaccent(lower(name))': 'gin_trgm_ops'})
    op.create_index('ix_institution_i18n_short_trgm', 'institution_i18n', [sa.literal_column('immutable_unaccent(lower(short_name))')], unique=False, postgresql_using='gin', postgresql_ops={'immutable_unaccent(lower(short_name))': 'gin_trgm_ops'})
    op.create_index('ix_offers_subject', 'offers', ['subject_id', 'is_active'], unique=False)
    op.drop_index(op.f('ix_subject_i18n_name_trgm'), table_name='subject_i18n', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('ix_subject_i18n_name_trgm', 'subject_i18n', [sa.literal_column('immutable_unaccent(lower(name))')], unique=False, postgresql_using='gin', postgresql_ops={'immutable_unaccent(lower(name))': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_availability_slots_period_is_bounded", "availability_slots")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subject_i18n_name_trgm', table_name='subject_i18n', postgresql_using='gin', postgresql_ops={'immutable_unaccent(lower(name))': 'gin_trgm_ops'})
    op.create_index(op.f('ix_subject_i18n_name_trgm'), 'subject_i18n', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('ix_offers_subject', table_name='offers')
    op.drop_index('ix_institution_i18n_short_trgm', table_name='institution_i18n', postgresql_using='gin', postgresql_ops={'immutable_unaccent(lower(short_name))': 'gin_trgm_ops'})
    op.drop_index('ix_institution_i18n_name_trgm', table_name='institution_i18n', postgresql_using='gin', postgresql_ops={'immutable_unaccent(lower(name))': 'gin_trgm_ops'})
    op.create_index(op.f('ix_institution_i18n_name_trgm'), 'institution_i18n', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
