#!/usr/bin/env bash
#
# Register this project's hostname with the shared Edge Caddy.
#
# The edge Caddyfile is shared infrastructure: several projects write to it, and
# a bad edit takes every site on the host down, not just this one. So the script
# owns exactly one marked block, takes a host-wide lock while it works,
# validates the *whole* resulting configuration before reloading, and puts the
# previous file back if anything fails.
#
# Environment (all required):
#   EDGE_CADDY_DIR           directory holding the edge project's compose file
#   EDGE_CADDY_COMPOSE_FILE  that compose file
#   EDGE_CADDY_SERVICE       service name inside it
#   EDGE_CADDYFILE           path on the host to the shared Caddyfile
#   EDGE_CADDY_CONFIG_PATH   path to the same file inside the container
#   ROUTE_FILE               the block to install, generated by CI

set -euo pipefail

MARKER_BEGIN="# BEGIN managed by teachers-catalog CI"
MARKER_END="# END managed by teachers-catalog CI"
LOCK_FILE="${EDGE_CADDY_DIR:?}/.github-actions-route.lock"

for var in EDGE_CADDY_DIR EDGE_CADDY_COMPOSE_FILE EDGE_CADDY_SERVICE \
           EDGE_CADDYFILE EDGE_CADDY_CONFIG_PATH ROUTE_FILE; do
  if [ -z "${!var:-}" ]; then
    echo "FATAL: $var is not set" >&2
    exit 1
  fi
done

[ -r "$ROUTE_FILE" ] || { echo "FATAL: cannot read $ROUTE_FILE" >&2; exit 1; }
[ -w "$EDGE_CADDYFILE" ] || { echo "FATAL: cannot write $EDGE_CADDYFILE" >&2; exit 1; }

compose() {
  docker compose -f "$EDGE_CADDY_COMPOSE_FILE" --project-directory "$EDGE_CADDY_DIR" "$@"
}

caddy_exec() {
  compose exec -T "$EDGE_CADDY_SERVICE" "$@"
}

main() {
  # The edge has to be up: reloading a stopped Caddy silently does nothing, and
  # the deployment would report success while the hostname resolves to nothing.
  if ! compose ps --status running --services | grep -qx "$EDGE_CADDY_SERVICE"; then
    echo "FATAL: edge service '$EDGE_CADDY_SERVICE' is not running" >&2
    exit 1
  fi

  # It must also be able to reach a loopback upstream, which only host
  # networking allows.
  local network_mode
  network_mode=$(compose ps --format json "$EDGE_CADDY_SERVICE" \
    | python3 -c 'import json,sys; print(json.loads(sys.stdin.read().splitlines()[0]).get("Networks",""))' 2>/dev/null || true)
  if [ "$network_mode" != "host" ]; then
    echo "WARNING: edge network mode reported as '${network_mode:-unknown}', expected 'host'" >&2
  fi

  local backup
  backup=$(mktemp)
  cp "$EDGE_CADDYFILE" "$backup"

  restore() {
    echo "restoring the previous edge Caddyfile" >&2
    cp "$backup" "$EDGE_CADDYFILE"
    caddy_exec caddy reload --config "$EDGE_CADDY_CONFIG_PATH" >/dev/null 2>&1 || true
  }

  local updated
  updated=$(mktemp)
  # Everything except our block, then our block appended. Rewriting rather than
  # patching in place is what makes this idempotent.
  awk -v b="$MARKER_BEGIN" -v e="$MARKER_END" '
    $0 == b { skip = 1; next }
    $0 == e { skip = 0; next }
    !skip   { print }
  ' "$EDGE_CADDYFILE" > "$updated"

  # Collapse any trailing blank lines the removal left behind.
  printf '%s\n' "$(cat "$updated")" > "$updated"
  {
    echo ""
    echo "$MARKER_BEGIN"
    cat "$ROUTE_FILE"
    echo "$MARKER_END"
  } >> "$updated"

  cp "$updated" "$EDGE_CADDYFILE"
  rm -f "$updated"

  # Validate the whole file, not just our block: a syntax error anywhere means
  # the reload takes down every site on the host.
  if ! caddy_exec caddy validate --config "$EDGE_CADDY_CONFIG_PATH" >/dev/null 2>&1; then
    echo "FATAL: the edge Caddyfile does not validate after the update" >&2
    caddy_exec caddy validate --config "$EDGE_CADDY_CONFIG_PATH" >&2 || true
    restore
    exit 1
  fi

  # Adapt to JSON and confirm our hostname and upstream really are in the result
  # — validation passes on a file where our block was silently dropped.
  local adapted
  adapted=$(caddy_exec caddy adapt --config "$EDGE_CADDY_CONFIG_PATH" 2>/dev/null || true)
  local host upstream
  host=$(awk 'NR==1 {gsub(/[{ ]/, ""); print}' "$ROUTE_FILE")
  upstream=$(grep -oE '127\.0\.0\.1:[0-9]+' "$ROUTE_FILE" | head -1)
  if ! grep -q "$host" <<<"$adapted" || ! grep -q "$upstream" <<<"$adapted"; then
    echo "FATAL: '$host' -> '$upstream' is missing from the adapted config" >&2
    restore
    exit 1
  fi

  if ! caddy_exec caddy reload --config "$EDGE_CADDY_CONFIG_PATH"; then
    echo "FATAL: the edge Caddy refused to reload" >&2
    restore
    exit 1
  fi

  rm -f "$backup"
  echo "edge route applied: $host -> $upstream"
}

# Serialised against other projects' deployments, which write to the same file.
exec 9>"$LOCK_FILE"
if ! flock -w 120 9; then
  echo "FATAL: timed out waiting for the edge route lock" >&2
  exit 1
fi

main
